steps:
# Step 1: Checkout kode dari repositori (main branch)
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '-b', 'main', '.']

# Step 3: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/crowdfunding/service-user-admin', '.']

# Step 4: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/crowdfunding/service-user-admin']

images:
- 'gcr.io/$PROJECT_ID/crowdfunding/service-user-admin'
