steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/crowdfunding/service-user-admin', '.']

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/crowdfunding/service-user-admin']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/crowdfunding/service-user-admin'
